#!/bin/bash

#divide by 3 and 5 but not devide by 15

for i in {1..100}; do

if ([ `expr $i % 3` == 0 ] || [ `expr $i % 5` == 0 ]) && [ `expr $i % 15` != 0 ];
then
    echo $i
fi;
done

=======================================================

#!/bin/bash

#Enter a number by user chrck its Even ya not

read -p "Enter a number----" i

if [ `expr $i % 2` == 0 ]
then
    echo "$i YES its a EVEN number"
else
    echo "$i NOT a EVEN"
fi

==========================================================

#!/bin/bash

#count number of "i" in mississipi

x=mississipi

grep -o "i" <<<$x | wc -l

============================================================
